### PR TITLE
initial build

### PR DESCRIPTION
**Pull request by wilberforce**
@gfwilliams 

I've updated the test travis build I have here:

https://github.com/wilberforce/Espruino/blob/travis/.travis.yml

to point to:

`- curl -Ls https://github.com/wilberforce/EspruinoBuildTools/raw/master/esp32/deploy/app.tgz | tar xfz -`
once this is update is committed, I can update to:

`- curl -Ls https://github.com/espruino/EspruinoBuildTools/raw/master/esp32/deploy/app.tgz | tar xfz -`

The current travis builds for:
* ESP32
* pico
* linux (linux binary does not seem to get copied to travis)
I wanted to check the matrix still worked and the gcc worked for different targets

You can see the outout here:
https://www.espruino.com/binaries/travis/master/

Next step is do add the actual build process....

Any chance you can add me to https://github.com/espruino/EspruinoBuildTools so can commit directly?

P. S Found this useful to syntax check .yml before committing:
https://lint.travis-ci.org/

### CODE REVIEW

**Comment by wilberforce** [comment]
Hmm.. this doesn't look right:

https://travis-ci.org/espruino/Espruino/builds/206508179

```
 2197.1
 no language set
 no environment variables set
 4 min 48 sec
```

I don't know if is something I've done or related to the S3 issue Amazon had today ;-(

I might need to roll back my changes and see if it still works..

**Comment by gfwilliams** [comment]
Strange... I've added you as a contributor hopefully so you should be able to use that repo - hopefully without the S3 issues it'll work when you update it to use `https://github.com/espruino/EspruinoBuildTools`

**Comment by wilberforce** [comment]
Ah -ok - I hadn't tried to push....

The issue with Travis CI just seems to be log files - as the build worked as the firmware ended up on https://www.espruino.com/binaries/travis/master/

**Comment by wilberforce** [comment]
I'm not sure where I can commit this update?

I see a box saying:
```
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.
```

**Comment by gfwilliams** [comment]
Sorry - try now

**Comment by wilberforce** [comment]
Thanks - I had to reply to an email too!

**Pull request merged**
