### PR TITLE
Added links to compiled firmware

### PR DESCRIPTION
**Pull request by psiphi75**

### CODE REVIEW

**Comment by gfwilliams** [comment]
@wilberforce I just wanted to check before merging - does this work ok?

**Comment by wilberforce** [comment]
@psiphi75 
```
ln -s Espruino/app/build/bootloader/bootloader.bin
ln -s Espruino/app/build/partitions_espruino.bin
ln -s Espruino/espruino_esp32.bin
```

At this point the working dir should already be `Espruino`

I think these should be:

```
ln -s app/build/bootloader/bootloader.bin
ln -s app/build/partitions_espruino.bin
```

With the latest build there should already be an espruino_esp32.bin in the current folder.

The `cd ..` should not be required, as you should already be in the `Espruino` folder

**Comment by psiphi75** [comment]
@wilberforce, correct.  Have made the changes and tested it.

**Comment by gfwilliams** [comment]
Great - merging then...

**Comment by markterrill** [comment]
Hi, quick note that with  1v99.3088 on the main /esp32 docu page there is a pytool flashing command that uses what I presume would be symlinks to the build files from the root espruino directory. They didn't exist for me, running find gave me the paths to then use a modified version:

```
esp-idf/components/esptool_py/esptool/esptool.py    \
        --chip esp32                                \
        --port /dev/tty.usbs*                         \
        --baud 921600                               \
        --before esp32r0                            \
        --after hard_reset write_flash              \
        -z                                          \
        --flash_mode dio                            \
        --flash_freq 40m                            \
        --flash_size detect                         \
        0x1000 build/espruino_1v92.3088_esp32/bootloader.bin \
        0x8000 build/espruino_1v92.3088_esp32/partitions_espruino.bin \
        0x10000 espruino_esp32.bin
```

**Pull request merged**
