### PR TITLE
Add Buildtools for arm64 host.

### PR DESCRIPTION
**Pull request by karelxkk**
Compiler to build Espruino for Arm32 on Android phone aarch64.

### CODE REVIEW

**Comment by karelxkk** [comment]
Optimize compatibility filename width existing toolchains for x86-64 arch.
Modification of the build scripts for Espruino is well on its way. I'm on it.

**Comment by karelxkk** [comment]
I will still fine-tune it so that the Espruino transition is smooth.  Need to set up processes to sync with Espruino repos.

**Comment by gfwilliams** [comment]
Thanks, but I'm not entirely sure this is something we want to support in this repo?

Perhaps others would like to chime in here but I don't know of anyone else building on Android.

And if you want to build, all you have to do is to manually install the toolchain yourself, so this is not a big deal. The compiler really exists in this repo (rather than being downloaded on demand) because when we're doing CI checks we end up having to download multiple times from ARM, and often that download would fail and cause the CI check to fail (hosting on GitHub was far more reliable).

Perhaps what we could do is add a PR that checks the architecture in `provision.sh` in the main repository, and if it is ARM64 then you download the file directly from ARM instead? End result is basically the same but it's not so hard for us to maintain

**Comment by karelxkk** [comment]
Hello. So I think this might be useful and save someone the trouble. Attached is a log of a successful build.As a reminder, Android already has some support for NRF (Banglejs2) in the apk.I recognize that this means more effort in administration. In my opinion, the provision.sh script would deserve to be improved with advanced diagnostics on dependency.Yes I have already come across the autobuil of Github. For now I would solve it by limiting python installation to aarch64 only and that should get the build on Github through. However, if we don't have pip and debian like distro preinstalled, the script will fail!!!We still need to investigate the compiler warnings. Such a check is too difficult for me - I don't know anything about it. The point is to make sure there are no errors in the code leading to BANGLEJS2 failure.The original motivation for this work was high energy prices, and after all android takes around 10W even with an external monitor. This was preceded by an effort to localize BANGLEJS2 into Czech lang. The localization system via %LANG does not work. I wanted to find out why and start from the ground up, i.e. the jswrap interpreter itself.If you can, check the attached listing to see if there is anything suspicious.Karel KadlecPrysk CZOdesláno z mého zařízení Galaxy
-------- Původní zpráva --------Od: Gordon Williams ***@***.***> Datum: 11.03.24  10:46  (GMT+01:00) Komu: espruino/EspruinoBuildTools ***@***.***> Cc: karelxkk ***@***.***>, State change ***@***.***> Předmět: Re: [espruino/EspruinoBuildTools] Add Buildtools for arm64 host. (PR #16) 
Thanks, but I'm not entirely sure this is something we want to support in this repo?
Perhaps others would like to chime in here but I don't know of anyone else building on Android.
And if you want to build, all you have to do is to manually install the toolchain yourself, so this is not a big deal. The compiler really exists in this repo (rather than being downloaded on demand) because when we're doing CI checks we end up having to download multiple times from ARM, and often that download would fail and cause the CI check to fail (hosting on GitHub was far more reliable).
Perhaps what we could do is add a PR that checks the architecture in provision.sh in the main repository, and if it is ARM64 then you download the file directly from ARM instead? End result is basically the same but it's not so hard for us to maintain

**Comment by gfwilliams** [comment]
Hi - I don't see the listing I'm afraid - maybe you need to update via GitHub at https://github.com/espruino/EspruinoBuildTools/pull/16

But as you say, a bit more diagnostics in the `provision.sh` script would be really good if you're happy to contribute that. At the very least detecting if `apt`/`pip` isn't there, and the arch would be great.

I think probably the issue you're having is Bangle.js only has ISO Latin characters built in: https://www.espruino.com/Fonts

It does support pebble's `pbf` format fonts now (and unicode) so you could handle the extra characters, but likely most apps would need to be modified to use the new fonts which is why we haven't done it yet.

Another option is to do like we do for Japanese/etc where we have *no* characters at all, and have everything converted to a bitmap:

https://github.com/espruino/BangleApps/tree/master/lang/unicode-based
gets converted to https://github.com/espruino/BangleApps/blob/master/lang/ja_JA.json using https://github.com/espruino/EspruinoAppLoaderCore/blob/bd301be3324775a8f464328ba9e34f750d503a2b/tools/language_render.js

**Comment by karelxkk** [comment]
[localhost_20240311120828.zip](https://github.com/espruino/EspruinoBuildTools/files/14559401/localhost_20240311120828.zip)
I'm sending the buildlog again. (I guess it didn't get through email.)
I'll try to use python3.12 again, since neither python3.10 nor 3.11 are compatible in Jammy. That's why I used python2.7 even though it's dead.

**Comment by karelxkk** [comment]
Hello. I sent the buld log to #16 and am considering opening it.I'm wondering how to install python3.12. I suggest using https://launchpad.net/~deadsnakes/+archive/ubuntu/ppaIt's a pretty big hit to the system and install add-pkg. The question is whether to trust this ppa.Alternatively one could build python3.12 from source, but again it's pretty harcore to install many dependencies.What is your judgement? Is nrfutil compatible with python3.12 at all?Not to keep things simple, I started tinkering with python3.12-venv. It makes sure that python3.12 is used and yet there is no need to change the preferred python version on the system. Pip is also much happier and doesn't grumble about library conflicts.For Czech localization, I'm more inclined to use the 8-bit iso-8859-2 encoding. It's not as universal as utf-8, but it can be better optimized.I didn't consider rewriting all applications, but taking the translation and processing it via %LANG for all applications.It's a lot. When I get around to it, I'd start translating it into ascii like in the days of computers I still remember. Write in Czech, but without the Czech characters.Then I'd add Espruino with iso-8859-2 fonts in the base and add a utf-8 to iso-8859-2 conversion for Czech to Espruino apps.This will provide support for cs_CZ and then I can start writing my own application. By the way, there is also a bug because I tried to write a translation for Settings and when using Czech characters, they didn't even register correctly to the system and couldn't open. After omitting the Czech characters, the back button still doesn't work in settings.Let's work on optimization. Don't compute everything on the watch, but give them code optimized already on Espruino-apps.Karel KadlecPrysk CZ-----------------------------------------------------------------------------------------------------Zdravím. Buld log jsem poslal do #16 a uvažuji o otevření.Přemýšlím, jak nainstalovat python3.12. Nabízí se použít https://launchpad.net/~deadsnakes/+archive/ubuntu/ppaJe to dost velký zásah do systému a instalovat add-pkg. Otázkou je, zda tomuto ppa důvěřovat.Alternativně by se dalo python3.12 sestavit ze zdrojového kódu, ale zase je to docela harcore doinstalovat mnoho dependencie.Jaký je Váš úsudek? Je vůbec nrfutil s python3.12 kompatibilní?Abych to neměl tak jednoduché, začal jsem laškovat s python3.12-venv. Zařídí, že se použije python3.12 a přitom není potřeba v systému měnit preferovanou verzi pythonu. Pip je také mnohem spokojenější a nenadává kvůli konfliktu knihoven.U lokalizace češtiny se spíše přiklánmím k použití 8-bit kódování iso-8859-2. Není to tak univerzální jako utf-8, ale lze lépe optimalizovat.Neuvažoval jsem o přepisování všech aplikací, ale že se překlad vezme a zpracuje přes %LANG pro všechny aplikace.Je toho hodně. Až se k tomu probiju, začal bych s překladem do ascii jako v dřevních dobách počítačů, které ještě pamatuji. Psát česky, ale bez českých znaků.Potom bych  přidal Espruino s iso-8859-2 fonty v základu a přidal pro češtinu do Espruino apps konverzi z utf-8 do iso-8859-2. Mimochodem je tam také chyba protože jsem zkoušel psát překlad pro Settings a při použití českých znaků se mi ani správně nezaregistrovaly do systému a nešly otevřit. Po vypuštění českých znaků stále v settings nefunguje tlačítko pro back.Tím bude zajištěna podpora pro cs_CZ a pak můžu začít psát vlastní aplikaci.Pasmatujme na optimalizaci. Nepočítat vše na hodinkách, ale dát jim kód optimalizovaný již na Espruino-apps.Karel KadlecPrysk CZOdesláno z mého zařízení Galaxy
-------- Původní zpráva --------Od: Gordon Williams ***@***.***> Datum: 11.03.24  12:54  (GMT+01:00) Komu: espruino/EspruinoBuildTools ***@***.***> Cc: karelxkk ***@***.***>, State change ***@***.***> Předmět: Re: [espruino/EspruinoBuildTools] Add Buildtools for arm64 host. (PR #16) 
Hi - I don't see the listing I'm afraid - maybe you need to update via GitHub at #16
But as you say, a bit more diagnostics in the provision.sh script would be really good if you're happy to contribute that. At the very least detecting if apt/pip isn't there, and the arch would be great.
I think probably the issue you're having is Bangle.js only has ISO Latin characters built in: https://www.espruino.com/Fonts
It does support pebble's pbf format fonts now (and unicode) so you could handle the extra characters, but likely most apps would need to be modified to use the new fonts which is why we haven't done it yet.
Another option is to do like we do for Japanese/etc where we have no characters at all, and have everything converted to a bitmap:
https://github.com/espruino/BangleApps/tree/master/lang/unicode-based
gets converted to https://github.com/espruino/BangleApps/blob/master/lang/ja_JA.json using https://github.com/espruino/EspruinoAppLoaderCore/blob/bd301be3324775a8f464328ba9e34f750d503a2b/tools/language_render.js

**Comment by gfwilliams** [comment]
Using `python3.12-venv` sounds like a good idea. Although I'm don't think we should make changes to the main Espruino repo just to support your very unique use case.

We currently use iso-8859-1 charset - I don't want to move to iso8859-2 as surely that's just going to annoy people from other countries that used characters that were in 8859-1 like À? Obviously if you want to do it for your own device then feel free but it's not something we could pull back.

As I mentioned before, PBF fonts allow us to include all characters without codepages, so I'd rather use that to fix the issue properly.

But also if you really need Czech right now you can render to bitmaps in the App Loader as I mentioned.

Please can you try and reply on GitHub rather than via email? I'm not sure if you can see but the whole message history is being included in your reply on https://github.com/espruino/EspruinoBuildTools/pull/16 which makes it very hard to read!

**Pull request closed without merging**
